name: Command Testing
# Push your desired Vendor Blobs in to your Pre-made Repository.
# Don't ever put your Github's Personal Access Token here as default value.
# If you are pushing in Github, be mindful in blobs size, 100MB maximum size per file.
# Other Repository Website don't have that limit, way bigger at least.
on:
  workflow_dispatch:
    inputs:
      DUMP_REPO:
        description: 'Android Dump' # Look for Android Dump in Github, or in Gitlab. Or dump your own.
        required: true
        default: 'https://codeberg.org/Firmware-Dump/android_dump_realme_9se'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
 
    - name: Check Out
      uses: actions/checkout@v3.1.0
      
    - name: Clone Android Dump Repository
      run: |
        mkdir workspace
        cd workspace
        echo "workspace=$(pwd)" >> $GITHUB_OUTPUT
        git clone ${{ github.event.inputs.DUMP_REPO }} temp
        echo "Done cloning."
      id: pwd

    - name: Compressing Modules
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar
        cd temp
        7z a Vendor-Modules-9SE.7z ${GITHUB_WORKSPACE}/workspace/temp/vendor_boot/ramdisk/lib/modules
        echo "Uploading as Github Release..."
      working-directory: workspace
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/Vendor-Modules-9SE.7z
        name: Vendor Modules
        tag_name: ${{ github.run_id }}
        body: |
          Device: Realme 9SE
          About: Vendor Modules
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
