name: Command Testing

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-12.1'
        
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    steps:

    - name: Prepare the Environment
      run: |
        sudo apt -y install git zip wget curl

    - name: Repo
      run: |
        git config --global advice.detachedHead false
        git clone https://android.googlesource.com/tools/repo -b v2.29 ~/bin
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
        
    - name: Download
      run: |
        mkdir workspace
        cd workspace
        wget https://codeberg.org/carlodeeCrypton/Personal-File-Dumping-Repo/raw/branch/main/Ulefone/Power6/recovery.img
        cd ..
        git clone https://github.com/cd-Spidey/Random.git ./randomfiles

    - name: Copy Files
      run: |
        cd workspace
        cp recovery.img ${GITHUB_WORKSPACE}/randomfiles/twrp_abtemplate

    - name: Zip Files
      run: |
        cd randomfiles/twrp_abtemplate
        zip -rv test-flashable-recovery.zip magiskboot META-INF/
        ls

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: randomfiles/test-flashable-recovery.zip
        name: For Testing Purposes - Stock Recovery Only
        tag_name: test-${{ github.run_id }}
        body: |
           - Hey
           - Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
