name: Command Testing

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-12.1'
        
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    steps:
    - name: Repo
      run: |
        git config --global advice.detachedHead false
        git clone https://android.googlesource.com/tools/repo -b v2.29 ~/bin
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
        
- name: Check Build Tree
      uses: haya14busa/action-cond@dependabot/npm_and_yarn/actions/core-1.9.1
      id: buildtree
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-11' || github.event.inputs.MANIFEST_BRANCH == 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-12.1' }}
        if_true: twrp
        if_false: omni

